{"name": "测试登录", "status": "broken", "statusDetails": {"message": "AttributeError: 'AssertUtil' object has no attribute 'log'", "trace": "self = <utils.AssertUtil.AssertUtil object at 0x1087f0460>, code = 404\nexpected_code = 200\n\n    def assert_code(self, code, expected_code):\n        \"\"\"\n        验证返回状态码\n        :param code:\n        :param expected_code:\n        :return:\n        \"\"\"\n        try:\n>           assert int(code) == int(expected_code)\nE           AssertionError\n\n../utils/AssertUtil.py:21: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testcase.test_Login.TestProjectModel object at 0x1080d9340>\n\n    @allure.title(\"测试登录\")\n    @allure.description(\"执行测试登录的结果是test\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login(self):\n        # 3、定义测试数据\n        conf_y = ConfigYaml()\n        url_path = conf_y.get_conf_url()\n        url = url_path + \"/sys/login\"\n        # url = \"http://ihrm-java.itheima.net/api/sys/login\"\n        data = {\"mobile\": \"13800000002\", \"password\": \"888itcast.CN764%...\"}\n        headers = {\"Content-Type\": \"application/json\"}\n        # 4、发送POST请求\n        # r = requests.post(url, json=data, headers=headers)\n        # r = requests_post(url, json=data, headers=headers)\n        request = Request()\n        r = request.post(url, json=data, headers=headers)\n        # 5、输出结果\n        # print(r.json())\n        print(r)\n        # 验证\n        # 返回状态码\n        code = r[\"code\"]\n>       AssertUtil().assert_code(code, 200)\n\ntest_Login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.AssertUtil.AssertUtil object at 0x1087f0460>, code = 404\nexpected_code = 200\n\n    def assert_code(self, code, expected_code):\n        \"\"\"\n        验证返回状态码\n        :param code:\n        :param expected_code:\n        :return:\n        \"\"\"\n        try:\n            assert int(code) == int(expected_code)\n            return True\n        except:\n>           self.log.error(\"code error,code is %s,expected_code is %s\" % (code, expected_code))\nE           AttributeError: 'AssertUtil' object has no attribute 'log'\n\n../utils/AssertUtil.py:24: AttributeError"}, "description": "执行测试登录的结果是test", "attachments": [{"name": "log", "source": "51d3d1ec-ea4e-43e5-8fce-6188ec702443-attachment.txt", "type": "text/plain"}], "start": 1695563741812, "stop": 1695563741965, "uuid": "b3724faa-59ad-4d04-b56b-e2ef67ade8c9", "historyId": "405be6d1429a066796c435ed527ca7af", "testCaseId": "405be6d1429a066796c435ed527ca7af", "fullName": "testcase.test_Login.TestProjectModel#test_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestProjectModel"}, {"name": "host", "value": "lifaliangdeMacBook-Air.local"}, {"name": "thread", "value": "39066-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_Login"}]}